warehouse = ["CPU", "Headphones"]
print("adding new products")
warehouse.append("laptop","mouse","keyboard","monitor") 
print(warehouse)
warehouse.append("monitor")
new_products = ["tablet","webcam"]
warehouse.extend(new_products)
print("after adding products: ",warehouse)
warehouse.remove("mouse")
print(warehouse)
warehouse.pop()
print(warehouse)
warehouse.count("laptop")
print(warehouse.index("monitor"))
warehouse.sort()
print(warehouse)
print(warehouse[::-1])
print(warehouse)
warehouse_backup = warehouse.copy()
print(warehouse_backup)
warehouse_backup.clear()